spring:
  # 이하 OAuth google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 532978985625-9qqp9npkeb8uu31u4ppf95netaeu6vt1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: d949fb810395dfd135b5b2c85366c48f
            client-secret: xg4HOv5IagLjmp8rLby53fFLb5YwwSpu
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8020/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: PQNFr2y_p7lj6557iK3p
            client-secret: 33tCgdBsxQ
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8020/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            issuerUri: https://accounts.google.com
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            userNameAttribute: sub
custom:
  paymentSecretKey: test_sk_KNbdOvk5rk4mn6z6mqE8n07xlzmj
  adminSignupKey: 19931103